### DISCUSSION TITLE
Asked to verify your email even emailVerified is true in db

### DISCUSSION THREAD

**Discussion by yang6n** [hatchet-dev/hatchet#1833] [Q&A]
Hi there!
I have installed the hatchet-ha helm chart (version 0.9.2) onto my k8s cluster via ArgoCD. 
I am able to access the dashboard, but it redirects me to the /onboarding/verify-email page. 
I have SERVER_AUTH_SET_EMAIL_VERIFIED set to true in the sharedConfig environment variables:
```
sharedConfig:
  enabled: true
  env:
    SERVER_AUTH_SET_EMAIL_VERIFIED: "true"
```

I also checked the db, the emailVerified column is true for the Admin user. 

Does anyone run into the same problem? any help or tips are appreciated, thanks in advance!
