### ISSUE TITLE
Hatchet Lite only generating localhost tokens

### ISSUE THREAD

**Issue by obermillerk** [hatchet-dev/hatchet#1115]
I'm trying to use hatchet lite as a simpler deployment for our small scale project, but I need a token that has a non-localhost host. Despite setting the `SERVER_GRPC_BROADCAST_ADDRESS` env variable in the docker compose for the hatchet-lite instance, tokens always seem to point to localhost.

I did this successfully using the go quickstart compose file and was able to connect using the non-localhost url that I set in that env var, but we're switching to hatchet lite in hopes of simpler deployment and this is a problem for us.

I'm hoping you can point me in the right direction. With the docker images the way they are, they're a black box to me so I'm not even sure where to look to try and see what I might be doing wrong or if there's a bug. Any help is appreciated.

In context, I'm trying to add the worker to the compose file so it's simpler to run, though I imagine this will also be a problem when we've published. This is the compose file I'm using:

```yaml
version: "3.8"
name: "hatchet-lite-dev"
services:
  postgres:
    image: postgres:15.6
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      - POSTGRES_USER=hatchet
      - POSTGRES_PASSWORD=hatchet
      - POSTGRES_DB=hatchet
    volumes:
      - hatchet_lite_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d hatchet -U hatchet" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  hatchet-lite:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-lite:latest
    # Set this to have a set hostname for other docker containers
    hostname: hatchet-engine
    ports:
      - "8888:8888"
      - "7077:7077"
    networks:
      # hatchet-bridge is a bridge network to connect disparate docker containers,
      # anything on this network should be able to connect to hatchet-engine hostname
      - hatchet-bridge
      - default
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
      DATABASE_URL: "postgresql://hatchet:hatchet@postgres:5432/hatchet?sslmode=disable"
      DATABASE_POSTGRES_PORT: "5432"
      DATABASE_POSTGRES_HOST: "postgres"
      SERVER_TASKQUEUE_RABBITMQ_URL: amqp://user:password@localhost:5672/
      SERVER_AUTH_COOKIE_DOMAIN: localhost
      SERVER_AUTH_COOKIE_INSECURE: "t"
      SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
      SERVER_GRPC_INSECURE: "t"
      # Changed this to try and generate tokens that other docker containers
      # can use to connect to this instance, but always seems to use localhost
      SERVER_GRPC_BROADCAST_ADDRESS: hatchet-engine:7077
      SERVER_GRPC_PORT: "7077"
      SERVER_URL: http://localhost:8888
      SERVER_AUTH_SET_EMAIL_VERIFIED: "t"
      SERVER_LOGGER_LEVEL: warn
      SERVER_LOGGER_FORMAT: console
      DATABASE_LOGGER_LEVEL: warn
      DATABASE_LOGGER_FORMAT: console
    volumes:
      - "hatchet_lite_rabbitmq_data:/var/lib/rabbitmq/mnesia"
      - "hatchet_lite_config:/config"
    healthcheck:
      test: [ "CMD-SHELL", "curl  -f http://localhost:8888/_health" ]
      timeout: 10s
      retries: 5
      start_period: 10s
  worker:
    build:
      context: .
      dockerfile: worker-dev.Dockerfile
    command: "go run ./cmd/worker"
    networks:
      - hatchet-bridge
      - default
    depends_on:
      hatchet-lite:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./**.go
          target: /app
          ignore:
            - ./server
        - action: rebuild
          path: go.mod

volumes:
  hatchet_lite_postgres_data:
  hatchet_lite_rabbitmq_data:
  hatchet_lite_config:

networks:
  hatchet-bridge:
    name: hatchet-bridge
    driver: bridge
```
