### ISSUE TITLE
Set Admin Email and Password via Environment Variables

### ISSUE THREAD

**Issue by AmsellemJoseph** [hatchet-dev/hatchet#1251]
Hey,

I'm trying to deploy Hatchet Lite using Docker Compose by following the official instructions:
🔗 [Hatchet Lite Self-Hosting Guide](https://docs.hatchet.run/self-hosting/hatchet-lite)

In the Accessing Hatchet Lite section ([link](https://docs.hatchet.run/self-hosting/hatchet-lite#accessing-hatchet-lite)), it states that a default user is created with the following credentials:

Email: admin@example.com
Password: Admin123!!
Is there a way to define the admin email and password using environment variables? This would allow us to avoid using the default credentials.

I tried changing the email directly in PostgreSQL, and it worked, but upon restarting my stack, a new user is generated again with the default credentials.

Is there a recommended approach to persist these credentials or override them during the initial setup?

Thanks in advance for your help!

**Comment by jshimko** [comment]
@AmsellemJoseph Haven't tried with the "Lite" version, but I do that with `ADMIN_EMAIL` and `ADMIN_PASSWORD` in the [Kubernetes/Helm version](https://docs.hatchet.run/self-hosting/kubernetes-helm-configuration).  Not sure why those vars aren't mentioned anywhere in the docs, but I originally found them in the Helm chart here:

https://github.com/hatchet-dev/hatchet-charts/blob/main/charts/hatchet-stack/templates/secret.yaml#L33-L34

So [this Helm config](https://github.com/hatchet-dev/hatchet-charts/blob/main/charts/hatchet-stack/values.yaml#L2-L15):

```yaml
sharedConfig: 
  serverUrl: "http://localhost:8080"
  serverAuthCookieDomain: "localhost:8080" # the domain for the auth cookie
  serverAuthCookieInsecure: "t" # allows cookies to be set over http
  serverAuthSetEmailVerified: "t" # automatically sets email_verified to true for all users
  serverAuthBasicAuthEnabled: "t" # allows login via basic auth (email/password)
  grpcBroadcastAddress: "localhost:7070" # the endpoint for the gRPC server, exposed via the `grpc` service
  grpcInsecure: "true" # allows gRPC to be served over http
  defaultAdminEmail: "admin@example.com" # in exposed/production environments, change this to a valid email
  defaultAdminPassword: "Admin123!!" # in exposed/production environments, change this to a secure password
 
```

Maps to [these environment variables](https://github.com/hatchet-dev/hatchet-charts/blob/main/charts/hatchet-stack/templates/secret.yaml#L27-L36).

```yaml
  SERVER_URL: "{{ .Values.sharedConfig.serverUrl | b64enc }}"
  SERVER_AUTH_COOKIE_DOMAIN: "{{ .Values.sharedConfig.serverAuthCookieDomain | b64enc }}"
  SERVER_AUTH_COOKIE_INSECURE: "{{ .Values.sharedConfig.serverAuthCookieInsecure | b64enc }}"
  SERVER_AUTH_SET_EMAIL_VERIFIED: "{{ .Values.sharedConfig.serverAuthSetEmailVerified | b64enc }}"
  SERVER_AUTH_BASIC_AUTH_ENABLED: "{{ .Values.sharedConfig.serverAuthBasicAuthEnabled | b64enc }}"
  SERVER_GRPC_BROADCAST_ADDRESS: "{{ .Values.sharedConfig.grpcBroadcastAddress | b64enc }}"
  SERVER_GRPC_BIND_ADDRESS: "{{ printf "0.0.0.0" | b64enc }}"
  SERVER_GRPC_INSECURE: {{ .Values.sharedConfig.grpcInsecure | b64enc }}
  ADMIN_EMAIL: "{{ .Values.sharedConfig.defaultAdminEmail | b64enc }}"
  ADMIN_PASSWORD: "{{ .Values.sharedConfig.defaultAdminPassword | b64enc }}"
```

Also see: https://docs.hatchet.run/self-hosting/configuration-options
