### ISSUE TITLE
[BUG] The replay and cancel buttons cause a 500 error

### ISSUE THREAD

**Issue by sh1man999** [hatchet-dev/hatchet#1598]
**Describe the issue**
The replay and cancel buttons cause a 500 error

![Image](https://github.com/user-attachments/assets/242772f8-a094-4e82-a605-a2f3d320102f)

**Environment**
- Engine: [Self-hosted v0.59.5]

**Comment by sh1man999** [comment]
```
172.19.0.1 - - [23/Apr/2025:09:16:51 +0000] "GET /api/v1/stable/tenants/707d0855-80ab-4e1f-a156-f1c4546cbf52/task-metrics?since=2025-04-22T09%3A16%3A33.384Z HTTP/1.1" 200 160 "http://localhost:8080/v1/runs?tenant=707d0855-80ab-4e1f-a156-f1c4546cbf52" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0"

2025-04-23T09:16:51.509Z WRN connecting to hatchet-engine:7077 without TLS service=server

2025-04-23T09:16:51.568Z ERR API error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.19.0.3:7077: connect: connection refused\"" host=localhost latency=62.719082 method=POST remote_ip=172.19.0.1 service=server status=500 uri=/api/v1/stable/tenants/707d0855-80ab-4e1f-a156-f1c4546cbf52/tasks/replay user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0"

172.19.0.1 - - [23/Apr/2025:09:16:51 +0000] "POST /api/v1/stable/tenants/707d0855-80ab-4e1f-a156-f1c4546cbf52/tasks/replay HTTP/1.1" 500 36 "http://localhost:8080/v1/runs?tenant=707d0855-80ab-4e1f-a156-f1c4546cbf52" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0"
```

**Comment by sh1man999** [comment]
docker-compose.yml
```
services:
  postgres:
    image: postgres:15.6
    command: postgres -c 'max_connections=1000'
    restart: unless-stopped
    hostname: "postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-hatchet}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-hatchet}
      - POSTGRES_DB=${POSTGRES_DB:-hatchet}
    ports:
      - "5435:5432"
    volumes:
      - hatchet_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB:-hatchet} -U ${POSTGRES_USER:-hatchet}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    restart: unless-stopped
    ports:
      - "5673:5672" # RabbitMQ
      - "15673:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER:-user}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS:-password}"
    volumes:
      - "hatchet_rabbitmq_data:/var/lib/rabbitmq"
      - "hatchet_rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf" # Configuration file mount
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
  migration:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-migrate:latest
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER:-hatchet}:${POSTGRES_PASSWORD:-hatchet}@postgres:5432/${POSTGRES_DB:-hatchet}"
    depends_on:
      postgres:
        condition: service_healthy
  setup-config:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-admin:latest
    command: /hatchet/hatchet-admin quickstart --skip certs --generated-config-dir /hatchet/config --overwrite=false
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER:-hatchet}:${POSTGRES_PASSWORD:-hatchet}@postgres:5432/${POSTGRES_DB:-hatchet}"
      SERVER_TASKQUEUE_RABBITMQ_URL: amqp://${RABBITMQ_USER:-user}:${RABBITMQ_PASS:-password}@rabbitmq:5672/
      SERVER_AUTH_COOKIE_DOMAIN: localhost:8080
      SERVER_AUTH_COOKIE_INSECURE: "t"
      SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
      SERVER_GRPC_INSECURE: "t"
      SERVER_GRPC_BROADCAST_ADDRESS: localhost:7077
      SERVER_DEFAULT_ENGINE_VERSION: "V1"
      SERVER_INTERNAL_CLIENT_INTERNAL_GRPC_BROADCAST_ADDRESS: hatchet-engine:7077
      SERVER_LIMITS_DEFAULT_TENANT_RETENTION_PERIOD: 720h # 30 days
    volumes:
      - hatchet_certs:/hatchet/certs
      - hatchet_config:/hatchet/config
    depends_on:
      migration:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
  hatchet-engine:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-engine:latest
    command: /hatchet/hatchet-engine --config /hatchet/config
    restart: unless-stopped
    depends_on:
      setup-config:
        condition: service_completed_successfully
      migration:
        condition: service_completed_successfully
    ports:
      - "7077:7070"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER:-hatchet}:${POSTGRES_PASSWORD:-hatchet}@postgres:5432/${POSTGRES_DB:-hatchet}"
      SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
      SERVER_GRPC_INSECURE: "t"
    volumes:
      - hatchet_certs:/hatchet/certs
      - hatchet_config:/hatchet/config
  hatchet-dashboard:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-dashboard:latest
    command: sh ./entrypoint.sh --config /hatchet/config
    ports:
      - 8080:80
    restart: unless-stopped
    depends_on:
      setup-config:
        condition: service_completed_successfully
      migration:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "postgres://hatchet:hatchet@postgres:5432/hatchet"
    volumes:
      - hatchet_certs:/hatchet/certs
      - hatchet_config:/hatchet/config
volumes:
  hatchet_postgres_data:
  hatchet_rabbitmq_data:
  hatchet_rabbitmq.conf:
  hatchet_config:
  hatchet_certs:

```
