### ISSUE TITLE
Add support for generic OIDC and OAuth connectors

### ISSUE THREAD

**Issue by abelanger5** [hatchet-dev/hatchet#44]
It should be possible to extend the auth mechanism to include more generic OIDC/OAuth integrations. 

The config can look something like [Dex OIDC connectors](https://dexidp.io/docs/connectors/oidc/). 

```yaml
connectors:
- type: oidc
  id: google
  name: Google
  config:
    # Canonical URL of the provider, also used for configuration discovery.
    # This value MUST match the value returned in the provider config discovery.
    #
    # See: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig
    issuer: https://accounts.google.com

    # Connector config values starting with a "$" will read from the environment.
    clientID: $GOOGLE_CLIENT_ID
    clientSecret: $GOOGLE_CLIENT_SECRET

    # Dex's issuer URL + "/callback"
    redirectURI: http://127.0.0.1:5556/callback
```
