### ISSUE TITLE
Running Hatchet behind Nginx over HTTPS results in HTTP/2 errors

### ISSUE THREAD

**Issue by rudimk** [hatchet-dev/hatchet#52]
Hey @abelanger5 - I'm running Hatchet on my lab server, where `hatchet-server` is running behind Nginx, and over SSL, on `https://hatchet.rudimk-infrastructure.com`. I'm able to access the dashboard, and I'm also able to use the CLI to authenticate against this instance, but running `hatchet init` in the quickstart's `smoke-test` module results in the following error:

```
could not run init: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: http2: frame too large"
```

A quick search threw this [comment](https://github.com/open-telemetry/opentelemetry-helm-charts/issues/646#issuecomment-1518031542) up, with the OTEL Helm charts. Wondering if there's something one can tweak in terms of config to get past it?

For reference, my `hatchet-server` config:

```yaml
runtime:
  port: 8080
  url: https://hatchet.rudimk-infrastructure.com
  runBackgroundWorker: true
  runRunnerWorker: false
  runTemporalServer: true
  runStaticFileServer: true
auth:
  cookie:
    domain: hatchet.rudimk-infrastructure.com
    insecure: false
fileStore:
  kind: local
  local: 
    directory: ./tmp/files
logStore:
  kind: file
  file: 
    directory: ./tmp/logs
```
