### ISSUE TITLE
Add metrics API and document usage with Keda

### ISSUE THREAD

**Issue by abelanger5** [hatchet-dev/hatchet#608]
Add a metrics API to return the number of queued step runs and workflow runs in various states. 

This should support filtering by metadata and workflow. We should document how Keda can be used to autoscale based on queue depth.

**Comment by eswolinsky3241** [comment]
@abelanger5 does this documentation exist yet? I'd be interested in learning best practices for autoscaling workers in Kubernetes.

**Comment by abelanger5** [comment]
Not yet, though I'm aware of some users that have gotten this set up successfully. Copying [a message](https://discord.com/channels/1088927970518909068/1300102869743308890/1301927403387617290) from a user on Discord here: 

> Here is my baseline KEDA config and this is working. I do not yet have it working to take into account rate limits but that might take me a little longer as it is a little further down on my priority list. The one part about this that I wish was better is that the URL requires the tenant. So I had to hardcode that. If you want to add this to the documentation or something I would recommend including the following process:
> If self hosting you will have to get the tenant id from the token: `kubectl get secrets/hatchet-client-config --template={{.data.HATCHET_CLIENT_TOKEN}} | base64 -d`
> Take the result of the command and place it here: https://jwt.io/
> You are looking for the 'sub' property in the payload which will tell you the tenant Id


```yaml 
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-hatchet-creds
  namespace: default
spec:
  secretTargetRef:
    - parameter: token
      name: hatchet-client-config
      key: HATCHET_CLIENT_TOKEN
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test
spec:
  maxReplicaCount: 10
  scaleTargetRef:
    name: test-deployment
  triggers:
  - type: metrics-api
    metadata:
      targetValue: "1"
      url: "http://hatchet-api.default.svc.cluster.local:8080/api/v1/tenants/707d0855-80ab-4e1f-a156-f1c4546cbf52/queue-metrics"
      valueLocation: total.numQueued
      authMode: "bearer"
    authenticationRef:
      name: keda-hatchet-creds
```
